### ISSUE TITLE
 Profession Mode bug (magazine)

### ISSUE THREAD

**Issue by k61514172** [falsechicken/SpawnKit#1]
12gauge shells, Military and colt magazine cannot spawn in profession mode of spawnkit plugins. I have not tried other magazine and bullet maybe they have the same problem. Also Military Ammunition Crate doesn't have this problem. By the way this is a great plugins, keep working with it :D

**Comment by falsechicken** [comment]
They should be able to. The soldier and police in the default profession mode config have them. I use them on my server lol. Do you have the latest version?

EDIT: I just tested the default profession mode config and confirmed that I do indeed get the Colt Mag.

**Comment by k61514172** [comment]
Thank for you reply:D
I found that the plugins works when there is a clothes for the kit, you may try
    [Items]
        [Item id="97" amount="1" /]
        [Item id="98" amount="4" /]
      [/Items]
i changed the >< to [] because it cannot show up

**Comment by falsechicken** [comment]
Ok. Ill test it.

**Comment by falsechicken** [comment]
Oh wow. I see.

**Comment by falsechicken** [comment]
It seems the hand slots are always empty.....

**Comment by falsechicken** [comment]
I no longer develop plugins. So I am putting the wontfix label here. But I am keeping the issue open for future forks.
