### ISSUE TITLE
On-Join not functioning.

### ISSUE THREAD

**Issue by ghost** [falsechicken/SpawnKit#3]
Played with the config for a couple hours, gave up, wrote my own, published it on rocket.

The below may be useful for helping ya figure out if someone joining is 'new' without wiping their inventory.

```
        private void eventPlayerConnected(RocketPlayer player) {

            int items = 0;
            foreach (SDG.Unturned.Items i in player.Inventory.Items) {
                items += i.getItemCount();
                }

            if (items == 0) {
                Log($"{player.CharacterName}'s inventory empty, granting loadout.");
                GrantLoadOut(player);
                }

            }
```

**Comment by falsechicken** [comment]
Sorry for the late reply. But as it says on the home page of my Rocket repositories I no longer develop plugins. The repository is remaining here in case someone wanted to fork.
